scope: clusterdb
namespace: /pgcluster/
# name of the node
name: slavedb


restapi:
  #  which address and port listen for restapi connection
  listen: 0.0.0.0:8888 
  # where connect
  connect_address: 192.168.2.17:8888
  # certfile: /var/lib/postgresql/15/ssl/cluster.pem
# rest-api certification, tls-connection
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

# ctl:
#   insecure: false # Allow connections to SSL sites without certs
#   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#   cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

# I use etcd3 version: https://www.percona.com/blog/upgrading-to-the-new-etcd-version-from-3-3-for-patroni/
etcd3: 
  hosts: 192.168.2.16:2379,192.168.2.17:2379,192.168.2.18:2379
  # cacert: /etc/etcd/ssl/ca.crt
  # cert: /etc/etcd/ssl/etcd-node3.crt  
  # key: /etc/etcd/ssl/etcd-node3.key 
# in the boostrap block is what will be done when initializing patroni

bootstrap:
  # Distributed Configuration Store - options bellow dcs will store in etcd
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    check_timeline: true

  initdb:
    # if problems with encoding appears, change value to cp1251    лалє psql \\! chcp 1251
    - encoding: UTF8
    - data-checksums
      
# parameters for futures creations of databases 
postgresql:
    listen: 0.0.0.0:5050
    connect_address: 192.168.2.17:5050

    data_dir: /var/lib/postgresql/15/data

    # important parameter. Enables fast sync for replics, without full restore from backup
    #use_pg_rewind: true

    pg_ctl: /usr/lib/postgresql/15/bin/pg_ctluster
    bin_dir: /usr/lib/postgresql/15/bin
    pg_pass: /tmp/pass
    #pg_bin: /usr/lib/postgresql/15/bin
    #remove_data_directory_on_rewind_failure: true
    parameters:
      ssl: 'on'
      ssl_cert_file: /var/lib/postgresql/15/ssl/cluster.crt
      ssl_key_file: /var/lib/postgresql/15/ssl/cluster.key
      max_connections: 50
      archive_command: '/usr/bin/pgbackrest --stanza=testcluster archive-push %p'
      archive_mode: on
      #use_pg_rewind: true
    authentication:
      superuser:
        username: postgres
        password: '65673608'
      
      replication:
        username: replicator
        password: '1234567'

    pg_hba:
    # IPv4 local connections:
    -  hostssl    all             all             127.0.0.1/32            scram-sha-256
    -  hostssl    all             all             0.0.0.0/0               scram-sha-256
    
    #-  hostssl    replication     all             192.168.2.0/24          scram-sha-256
    -  hostssl    replication     all             192.168.2.16/32         scram-sha-256
    -  hostssl    replication     all             192.168.2.17/32         scram-sha-256
    -  hostssl    replication     all             127.0.0.1/32            scram-sha-256 
    -  local      replication     all                                     trust
    -  local      all             all                                     peer  
    #-  local      all             all                                     scram-sha-256
    #   use_unix_socket: true
    #   pgpass: /tmp/pgpass

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false